// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanupExpiredMagicLinks(ctx context.Context) error
	CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id pgtype.UUID) error
	GetMagicLinkByToken(ctx context.Context, token string) (GetMagicLinkByTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InvalidateUserMagicLinks(ctx context.Context, arg InvalidateUserMagicLinksParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UseMagicLink(ctx context.Context, id pgtype.UUID) (MagicLink, error)
	VerifyUserEmail(ctx context.Context, id pgtype.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
