services:
  # Development overrides for the app service
  app:
    build:
      context: ../../
      dockerfile: docker/app/Dockerfile.dev
    container_name: trading_alchemist_app_dev
    environment:
      - APP_ENV=development
      - APP_BASE_URL=http://localhost:8080
      - JWT_SECRET=dev-secret-key-change-in-production
      - MAGIC_LINK_TTL=15m
    volumes:
      # Mount source code for hot-reload
      - ../../:/app
      # Exclude node_modules and other directories
      - /app/tmp
      - /app/vendor
    command: ["air", "-c", ".air.toml"]
    # Override healthcheck for development
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development database with different port to avoid conflicts
  postgres:
    ports:
      - "5433:5432"  # Use different port for dev to avoid conflicts 